spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    add-properties: false
  freemarker:
    cache: false
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
  jwt:
    secret: govlepel@$&
